name: Run Python Script on Webhook

on:
  workflow_dispatch: # Permite disparo manual via webhook ou interface do GitHub
  repository_dispatch: # Webhook externo pode disparar este evento

jobs:
  run_python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openai requests

    - name: Run Python Script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
      run: |
        python main.py '${{ github.event.client_payload }}'
